language: node_js
node_js:
    - stable
branches:
    only:
        - master
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g @angular/cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: dist/user-list
    keep_history: true
    on:
        branch: master
env:
    global:
        secure: rNNtOhaxXKKcYoiMCnwtoPpunbbQzj9msTxWtEg+86PAtP9JKiPOYky1Hw7f3grotJQ+5vBtScL6yThjkM7zoySJ8ugCejpktoAPpo0XnKODVKXVav3Nw2puosscI/1iToije+nVrlqkNb+Qr8d9Ur1Jy9UTQQGlgv6Bi9ZD3dTwCEr01ywTF80NRUo9+516Dn8BN6DC++0lCf/YxvHAs08gxasH8IkuOrs4kRTzFJXrVPF6Izx2L5CVbsrkVB9moRmqcusuH8LVovzq0RzSQdspiq+viS1tfVMCgsd8MNE3iInJNJPlcEiXC2lso90snHTtPtLmIkzyhA4lRFGP+iQk/yfR4tT5Cet81C1LnoHVdIq6RudeNlJJ6KRWghLGkAZyRmQOn5/BjGDXnLb8DfngHoX7mB6phWlFSnIae8RgZ032P4jpWgF3eqLvWVT+4vliUVLrIQIDuHc8O9le7BuqdrmAKTaB86bifBRwz2mlbF4bXFQ8qL7mKh5TIXaTkm+bhWnnibzR3VfFvTS2df9S39vEjgMppN7Eq5h8jLuxlqIiT/l6/GfjQ9GhlVirEcpQ66q0dTKKcBhg6XBpNIYHV51feoQ6/FzmoN2p6q4m0UnJVe6UX24X2/F7J70XASsQbMbk50qio+2VfREg2NYa9Is+NmM9W61QOFHicDY=
