language: node_js
node_js:
    - stable
branches:
    only:
        - master
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g @angular/cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: dist/github-users
    keep_history: true
    on:
        branch: master
env:
    global:
        - secure: Fu5wFkIKF6iRHmzn4OboQ4YLyXQWZKbf9x08avUfQISyoSwvDGURs/kemervI1qQbC5pxNJ8DgIX9LAhVVBydyRBDmdUldvDzw051zawFyR30KhVHZPNFRrYhYFJB4yMu+C26hQKe7/M6Q8xaQCob04bDDhjEOgWLSeFLchukHclVBWa2dRcjvu/71fKmEvgyK8nacxpf9DPlNhhNKyj9f2V56X8CL1PLACPIsBTr4U96gwkqNfV0LzWd7Q+tVUl5oTC6v0ZabRaR42oAm9SA/zoL6/gz8DvQDlMeJHkJC8ERpITd6knPQMqUweM+X56Rz47CCP1jjEvpmWGI2v5MmyrZEEz3USub51KiDBuLmkB4lSvF9vrCNx+r3yEZj0xIft3J9zMrC09SxoLgkJy3lTxI3bKpH0Y1wm9Ut9HdBsFktqugjneugkLXJY15m5IVi82gnJF+vsV09jlVmEnFMkooE763E5tGbg+SX/xeQlzwLJDPBf9E3GS5KKn9fQCHdmQjsmim7UMotRB91gFnB4ubWDN9b1yO5dkFLsLwMkfMkyVgpKCnmQHlnjvAd6C0hdmjkWs5MuDm8Bl2JH7PraU4e8qL2nl7/iRatXvUewftxXQGxZkBoonoz/o6jncMjYtgOzg569UffZX4E5KLGVL+eS8SrqgWsRdwuJjHsU=
