language: node_js
node_js:
    - stable
branches:
    only:
        - master
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g @angular/cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: dist/github-users
    keep_history: true
    on:
        branch: master
env:
    global:
        - secure: djdzQBg3yTigMeegZbEj+MGteotBgw1OjhAlaXv1FPt7+iizAOkgeQ3uRNxSpZxIat7/ezWXSJ0pXYxwwpKXzJk13jzmIxbmI4PWu1JKMEy1kstIzJvkmRacdHwjJxOqeY6e5fVjliytanMnDGOK/9t5VlK7/XbGxpe87OI6/6r27nwzXDHZtYBchSJvhD4TVF/RvAx8XpyCsEVNvG8vxMqZ4TltkDwxm+30xLyuZh07Wtke/3GPBp2/PE3LOwK9PaqldGN8UvbP5iRORiPnfIZbXJPLX70enWmu36uz57ylFQloOWElWr3KAgN/EHwcbkor8B0ZCiFQmI9IMPfAkQR6ze6kzZfw9BCePvj+SyneTkJgtnvOF08F3RyehIj02WjpR+yIitw/pR30kTklrh5UyRTXicIYxMBJs9sTUE4vM5V7igNRcub2epIVxgVTRQ+g/FpkcSWS4pZw4a2vkGDiSTr81NmV6vvZKn4hbDSS1//7CSythJh3XG7/LeVeyKOhEaGNs5vXzpjSWWkrc1A3qK2UccFExRZ39bUU0NOwipL9ilGRnxCWtHuQuY4et8hCdm21cYWukY2gGw6eZikyutoWvPIEsZBJqw+g1WDEJzQfQjf0+9/5US8jW7Zyr4F7zALtIP9G6ok4/GCWd9OiZDofTd7SsG+ZWq2XCu8=
